name: Semgrep Scan

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: semgrep/semgrep-action@v1
        with:
          config: >
            p/typescript
            p/owasp-top-ten
            p/security-audit
